openapi: 3.0.2
info:
  description: Product catalogue APIs for Suppliers
  version: 0.0.1-SNAPSHOT
  title: Products Inventory API for Greengrocers Suppliers
  contact:
    email: api-admin@greengrocers-sampleapis.com
servers:
  - url: https://localhost:8080/v1
    description: local server

tags:
  - name: Supplier API
    description: Operations with Supplier API

paths:
  /suppliersHealthCheck:
    get:
      tags:
        - developers
      summary: A health check ping for suppliers APIs
      description: Ping API and may want to use before calling the other heavy APIs
      operationId: healthCheck
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckStatus'
              example: healthy
        '400':
          description: Not healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckStatus'
              example: One or more health checks are failing
  /suppliers:
    get:
      tags:
        - admins
      summary: list of all available suppliers
      operationId: getSuppliers
      description: |
        Fetch all the Suppliers of GreenGrocers (admin only)
      responses:
        '200':
          description: returns all the available suppliers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierSummary'
    post:
      tags:
        - admins
      summary: Add a new supplier
      operationId: addSupplier
      responses:
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/Supplier'
  '/suppliers/{supplierId}':
    get:
      tags:
        - admin
      summary: Fetch a specific Supplier details by given supplier code
      operationId: getSupplierBySupplierCode
      description:
        Return a Single Supplier
      parameters:
        - name: supplierId
          in: path
          description: supplier Id of Supplier details to be returned
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
            application/xml:
              schema:
                $ref: '#/components/schemas/Supplier'
        '400':
          description: Invalid ID supplied
        '404':
          description: Supplier not found
components:
  schemas:
    HealthCheckStatus:
      type: object
      properties:
        appId:
          type: string
        healthState:
          type: string
          description: state of the app health
          enum:
            - Down
            - Up
            - Unknown
    SupplierSummary:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: supplier IDs as Array object
          items:
            $ref: '#/components/schemas/Supplier'
      example:
        - id: 343-23232-232323
        - id: 342-34355-543534
    Supplier:
      type: object
      required:
        - supplierId
        - supplierCode
        - supplierName
        - supplierType
      properties:
        supplierId:
          type: string
        supplierCode:
          type: string
        supplierName:
          type: string
        supplierType:
          type: integer
          format: int32

  requestBodies:
    Supplier:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Supplier'
        application/xml:
          schema:
            $ref: '#/components/schemas/Supplier'
      description: Supplier object that needs to be added to the Suppliers
      required: true